var ingilizceturkce2etapfiilcekimleri = {
    "arise, arose, arisen": "Ayağa kalkmak",
"awake, awoke/awakened, awoken": "Uyanmak",
"be, was/were, been": "Olmak, bulunmak",
"bear, bore, born/borne": "Dayanmak",
"beat, beat, beaten/beat": "Çırpmak, vurmak",
"become, became, become": "Haline gelmek",
"befall, befell, befallen": "Başına gelmek",
"begin, began, begun": "Başlamak, baş etmek",
"behold, beheld, beheld": "Bakmak, dikkat etmek",
"bend, bent, bent": "Bükmek, bükülmek",
"bet, bet/betted, bet/betted": "İddaya girmek",
"bid, bid, bid": "Teklif etmek",
"bind, bound, bound": "Bağlamak",
"bite, bit, bitten": "Isırmak",
"bleed, bled, bled": "Akmak",
"blow, blew, blown": "Esmek",
"break, broke, broken": "Bozmak, kırmak",
"breed, bred, bred": "Yavrulamak",
"bring, brought, brought": "Getirmek",
"broadcast, broadcast/broadcasted, broadcast/broadcasted": "Yayımlamak",
"browbeat, browbeat, browbeat": "Gözdağı vermek",
"build, built, built": "İnşaa etmek",
"burn, burnt/burned, burnt/burned": "Yakmak",
"burst, burst, burst": "Patlamak",
"bust, busted/bust, busted/bust": "Batırmak",
"buy, bought, bought": "Satın almak",
"cast, cast, cast": "Atfetmek, atmak",
"catch, caught, caught": "Yakalamak",
"choose, chose, chosen": "Seçmek",
"cling, clung, clung": "Tutunmak",
"come, came, come": "Gelmek",
"cost, cost, cost": "Mal olmak",
"creep, crept, crept": "Sürünmek",
"cut, cut, cut": "Kesmek",
"deal, dealt, dealt": "İlgilenmek",
"dig, dug, dug": "Kazmak",
"dive, dived/dove, dived": "Dalmak",
"do, did, done": "Yapmak",
"draw, drew, drawn": "Çekmek, çizmek",
"dream, dreamt/dreamed, dreamt/dreamed": "Hayal kurmak",
"drink, drank, drunk": "İçmek",
"drive, drove, driven": "Araba sürmek",
"dwell, dwelt/dwelled, dwelt/dwelled": "İkamet etmek",
"eat, ate, eaten": "Yemek yemek",
"fall, fell, fallen": "Düşmek",
"feed, fed, fed": "Beslemek",
"feel, felt, felt": "Hissetmek",
"fight, fought, fought": "Dövüşmek",
"find, found, found": "Bulmak",
"fit (to be right size), fit, fit": "Uymak",
"fit (to tailor, change size), fit/fitted, fit/fitted": "Yakıştırmak",
"flee, fled, fled": "Kaçmak",
"fling, flung, flung": "Atılmak",
"fly, flew, flown": "Uçmak",
"forbid, forbade, forbidden": "Yasaklamak",
"forecast, forecast, forecast": "Tahmin etmek",
"forego, forewent, foregone": "Bırakmak",
"foresee, foresaw, foreseen": "İleriyi görmek",
"foretell, foretold, foretold": "Gaipten haber vermek",
"forget, forgot, forgotten": "Unutmak",
"forgive, forgave, forgiven": "Affetmek",
"forsake, forsook, forsaken": "Bırakmak",
"freeze, froze, frozen": "Donmak",
"get, got, gotten/got": "Almak, elde etmek",
"give, gave, given": "Vermek",
"go, went, gone": "Gitmek",
"grind, ground, ground": "Öğütmek",
"grow, grew, grown": "Büyümek",
"hang, hung, hung": "Asmak",
"have, had, had": "Sahip olmak",
"hear, heard, heard": "Duymak, işitmek",
"hide, hid, hidden": "Gizlemek, saklanmak",
"hit, hit, hit": "Çarpmak, vurmak",
"hold, held, held": "Taşımak, tutmak",
"hurt, hurt, hurt": "Acımak, acıtmak",
"input, input, input": "(veri, vb.) girmek",
"inset, inset, inset": "Arasına koymak",
"interbreed, interbred, interbred": "Melezlemek",
"interweave, interwove, interwoven": "Beraber dokumak",
"keep, kept, kept": "Saklamak",
"kneel, knelt/kneeled, knelt/kneeled": "Diz çökmek",
"knit, knit/knitted, knit/knitted": "Örmek",
"know, knew, known": "Bilmek",
"lay, laid, laid": "Sermek",
"lead, led, led": "Öncülük etmek",
"lean, leaned/leant, leaned/leant": "Dayamak, yaslanmak",
"leap, leapt/leaped, leapt/leaped": "Atlamak",
"learn, learned/learnt, learned/learnt": "Öğrenmek",
"leave, left, left": "Ayrılmak",
"lend, lent, lent": "Ödünç vermek",
"let, let, let": "İzin vermek",
"lie, lay, lain": "Uzanmak",
"light, lit/lighted, lit/lighted": "Işık vermek",
"lose, lost, lost": "Kaybetmek",
"make, made, made": "Yapmak",
"mean, meant, meant": "Anlamına gelmek",
"meet, met, met": "Tanışmak, buluşmak",
"mishear, misheard, misheard": "Yanlış duymak",
"mislay, mislaid, mislaid": "Kaybetmek",
"mislead, misled, misled": "Yanlış yönlendirmek",
"misread, misread, misread": "Yanlış okumak",
"misspell, misspelled/misspelt, misspelled/misspelt": "Yanlış hecelemek",
"mistake, mistook, mistaken": "Yanlış anlamak",
"misunderstand, misunderstood, misunderstood": "Yanlış anlamak",
"mow, mowed, mowed/mown": "Biçmek",
"outbid, outbid, outbid": "Artırmak",
"outdo, outdid, outdone": "Bastırmak, fark atmak",
"outgrow, outgrew, outgrown": "Aşmak, hızlı büyümek",
"outrun, outran, outrun": "Daha hızlı koşmak",
"outsell, outsold, outsold": "Daha çok satmak",
"overcast, overcast, overcast": "Bulutla kaplamak",
"overcome, overcame, overcome": "Alt etmek",
"overdo, overdid, overdone": "Dozunu kaçırmak",
"overdraw, overdrew, overdrawn": "Fazla para çekmek",
"overeat, overate, overeaten": "Fazla yemek yemek",
"overhang, overhung, overhung": "Üzerinden sarkmak",
"overhear, overheard, overheard": "Gizlice dinlemek",
"overlay, overlaid, overlaid": "Bindingelik",
"overlie, overlay, overlain": "Üzerine yatmak",
"overpay, overpaid, overpaid": "Fazla ödemek",
"override, overrode, overridden": "Ağır basmak",
"overrun, overran, overrun": "Aşmak",
"oversee, oversaw, overseen": "Bakmak",
"oversell, oversold, oversold": "Fazla satış yapmak",
"overshoot, overshot, overshot": "Aşırılığa kaçmak",
"oversleep, overslept, overslept": "Fazla uyumak",
"overtake, overtook, overtaken": "Sollamak",
"overthrow, overthrew, overthrown": "Altüst etmek",
"partake, partook, partaken": "Andırmak",
"pay, paid, paid": "Ödemek",
"plead, pled/pleaded, pled/pleaded": "Savunma yapmak",
"pre-set, pre-set, pre-set": "Önceden kurmak",
"proofread, proofread, proofread": "Prova okumak",
"prove, proved, proven/proved": "İspat etmek",
"put, put, put": "Koymak",
"quit, quit/quitted, quit/quitted": "Bırakmak",
"read, read, read": "Okumak",
"rebind, rebound, rebound": "Tekrar ciltlemek",
"rebuild, rebuilt, rebuilt": "Yeniden inşaa etmek",
"recast, recast, recast": "Değişiklik yapmak",
"redo, redid, redone": "Yeniden yapmak",
"re-lay, re-laid, re-laid": "Yeniden döşemek",
"remake, remade, remade": "Tekrar yapmak",
"repay, repaid, repaid": "Geri vermek",
"rerun, reran, rerun": "Yeniden göstermek",
"resell, resold, resold": "Satmak",
"reset, reset, reset": "Ayarlamak",
"rethink, rethought, rethought": "Durup düşünmek",
"rewind, rewound, rewound": "Geri sarmak",
"rewrite, rewrote, rewritten": "Yeniden yazmak",
"rid, rid, rid": "Başından atmak",
"ride, rode, ridden": "Binmek (at)",
"ring, rang, rung": "Çalmak",
"rise, rose, risen": "Doğmak, yükselmek",
"run, ran, run": "Çalıştırmak, koşmak",
"say, said, said": "Söylemek",
"see, saw, seen": "Görmek",
"seek, sought, sought": "Aramak, aranmak",
"sell, sold, sold": "Satmak",
"send, sent, sent": "Göndermek",
"set, set, set": "Bir şekle sokmak",
"sew, sewed, sewn/sewed": "Dikiş dikmek",
"shake, shook, shaken": "Çalkalamak, sarsmak",
"share, shared, shared": "Paylaşmak",
"shear, sheared, shorn/sheared": "Kırpmak",
"shed, shed, shed": "Dökmek (gözyaşı)",
"shine, shined/shone, shined/shone": "Parlamak",
"shoot, shot, shot": "Ateş etmek",
"show, showed, shown/showed": "Göstermek",
"shrink, shrank/shrunk, shrunk": "Büzülmek",
"shut, shut, shut": "Kapatmak",
"sing, sang, sung": "Şarkı söylemek",
"sit, sat, sat": "Oturmak",
"slay, slew, slain": "Katletmek",
"sleep, slept, slept": "Uyumak",
"slide, slid, slid": "Akıp gitmek",
"sling, slung, slung": "Sapanla (taş) atmak",
"slit, slit, slit": "Kesmek, sökmek",
"smell, smelled/smelt, smelled/smelt": "Koklamak",
"speak, spoke, spoken": "Konuşmak",
"speed, sped/speeded, sped/speeded": "Sürat yapmak",
"spell, spelled/spelt, spelled/spelt": "Hecelemek",
"spend, spent, spent": "Harcamak",
"spin, spun, spun": "Döndürmek",
"spit, spit/spat, spit/spat": "Tükürmek",
"split, split, split": "Bölmek",
"spoon-feed, spoon-fed, spoon-fed": "Şımartmak",
"spread, spread, spread": "Yayılmak",
"spring, sprang/sprung, sprung": "Yay gibi fırlatmak",
"stand, stood, stood": "Ayakta durmak",
"steal, stole, stolen": "Çalmak, aşırmak",
"stick, stuck, stuck": "Batırmak",
"sting, stung, stung": "Batmak",
"stink, stank/stunk, stunk": "Kokmak",
"strew, strewed, strewn/strewed": "Dağılmak",
"stride, strode, stridden": "Aşmak",
"strive, strove, striven": "Çabalamak",
"strike (delete), struck, stricken": "Çarpmak",
"strike (hit), struck, struck/stricken": "Vurmak",
"string, strung, strung": "Takmak (ip vb.)",
"strive, strove/strived, striven/strived": "Çabalamak",
"swear, swore, sworn": "Yemin etmek",
"sweep, swept, swept": "Süpürmek",
"swell, swelled, swollen/swelled": "Kabarmak",
"swim, swam, swum": "Yüzmek",
"swing, swung, swung": "Salıncakta sallanmak",
"take, took, taken": "Almak",
"teach, taught, taught": "Öğretmek",
"tear, tore, torn": "Yırtmak",
"tell, told, told": "Anlatmak",
"think, thought, thought": "Düşünmek",
"throw, threw, thrown": "Atmak",
"thrust, thrust, thrust": "Batırmak",
"tread, trod, trodden/trod": "Adımlamak",
"unbind, unbound, unbound": "Açmak, bağını çözmek",
"underlie, underlay, underlain": "Asıl nedeni olmak",
"understand, understood, understood": "Anlamak",
"undertake, undertook, undertaken": "Üstlenmek",
"underwrite, underwrote, underwritten": "Altına yazmak",
"undo, undid, undone": "Geri almak",
"unwind, unwound, unwound": "Çözmek",
"uphold, upheld, upheld": "Desteklemek",
"upset, upset, upset": "Keyfini kaçırmak",
"wake, woke/waked, woken/waked": "Canlanmak",
"wear, wore, worn": "Giymek",
"weave, wove, woven": "Dokumak",
"wed, wed/wedded, wed/wedded": "Adamak",
"weep, wept, wept": "Ağlamak",
"wet, wet/wetted, wet/wetted": "Islatmak",
"win, won, won": "Kazanmak",
"wind, wound, wound": "Dolamak, sarmak",
"withdraw, withdrew, withdrawn": "Çekmek",
"wring, wrung, wrung": "Acttmak",
"write, wrote, written": "Yazmak"
}