var turkceingilizce3 = {
    "(İzin veriyorum) Gidebilirsin. ":" You can go",
    " (Dikkatli ol) Babam gelebilir":" My father may come ",
    " (Senin için dünyayı) yakarım":" I would burn",
    " (Üzülme akşama) tamamlarız":" We will complete ",
    " (Her gün) konuşuyorum ":" I (do) speak",
    " (İşim bu) Konuşurum ":" I (do) talk",
    " (Hiç sanmıyorum ama) gelebilir":" He/She/It might come",
    " (İstesen arkadaş) olabiliriz":" We could be ",
    "(Burası tehlikeli) kaçmalısın":" You must escape ",
    " (Söz seni yarın) arayacağım ":" I am going to call",
    " (Biz) Aileyiz(dir)":" We are a family",
    " (Of çok fazla kan) kaybediyor":" He/She/It is losing",
    " (Bu hikâyeyi) dinlemen lazım":" You should listen",
    " (Akşam olmadan) ayrılmak zorundayız":" We have to leave",
    " (Dün futbol) oynadık":" We played (X2)",
    " (2001’de) Yeni bir dönem başladı":" A new era has started (X3)",
    " (Daha hızlı) yürüseler iyi olur":"They had better walk ",
    " (Bugün yolda) para buldum ":" I have found money (X3)",
    " (Geçen akşam çok) gülmüştük":" We had laughed ",
    " (İsteseydin beni) durdurabilirdin":" You could have stopped",
    " (Farkında mısın) babam değişmiş":" My father has changed",
    " (Nihayet şirketimizi) açmış bulunuyoruz":" We have opened ",
    " (Önemli bir noktaya) varmış durumdayız ":" We have arrived",
    " (Dikkat etsene) hoca duyabilirdi!":" The teacher might have heard",
    " (Sen oku ben ceketimi) satarım":" I would sell",
    " (Şu anda kalp atışını) duyabiliyorum ":" I can hear ",
    " (İçeri gelsene) dans ediyoruz":" We are dancing ",
    "(Görünür olmazsan) İnsanlar seni unutabilir":" People may forget you",
    " Anıtkabir’i ziyaret edeceğim ":" I am going to visit Anıtkabir",
    " (Eskiden daha) korkaktın":" You were coward ",
    " (Çocukken) su satardım":" I would/used to sell water",
    " (Dün bu saatte) kitap okuyorlardı":" They were reading books",
    " (Gençliğimde insanlara) güveniyordum":" I would/used to trust ",
    " Dedem (Sağken beni tek eliyle) kaldırabiliyordu ":" My grandfather would lift",
    " (Eskiden) kibardın":" You were kind ",
    " Yüzümü yıkayacaktım.":" I was going to wash  my face",
    " (Çağırsaydın) gelirdim":" I would have come (X3)",
    " (Çocukken hep) gelirdim":" I would/used to come ",
    "(Ben dünyanın en büyük aşığı) olabilirim":" I could be ",
    " (Bu sene okul 1.si) olabilirim ":" I may be",
    " (O gün) farketmiştim.":" I had noticed",
    " (aman tanrım) terlemişsin":" You have sweated",
    " (Borcunu zamanında) ödemeliydin":" You should have paid",
    " (Erken kalktım çünkü) çalışmam lazımdı":" I had to work",
    " (O sırada İngilizce) konuşuyorduk":" We were speaking ",
    " (Şu anda) Hoca konuşuyor":" The teacher is speaking ",
    " (Dün) taşındık":" We moved ",
    " (Tüh, sence de) reddetmeli miydim?":" Should I have refused?",
    " (Ne yani) bakmamam mı lazımdı? ":" Should I not have  looked?"
};
