const motivationalQuotes = [
            "Bugün sigarasız geçirdiğin her dakika, yarın için daha güçlü bir temel oluşturur! 💪",
            "Sen sigara içmek zorunda olan biri değilsin. Sen özgürsün! 🦋",
            "Her geçen gün, vücudun iyileşiyor ve güçleniyor! 🌱",
            "Sigarayı bırakmak imkansız değil, sadece önemli bir karardır! ✨",
            "Kendine verdiğin bu hediyeyi kutla, bunu hak ediyorsun! 🎁",
            "Bugün bir gün daha güçlüsün, bir gün daha özgürsün! 🌟",
            "Zorluklara göğüs geriyor ve kazanıyorsun! Her gün bir zafer! 🏆",
            "Ciğerlerin şükrediyorlar, cüzdanın mutlu, sağlığın yerinde! ❤️",
            "Eski alışkanlıkların seni tanımlamaz. Yeni başarıların tanımlar! 🚀",
            "Her gün, sigara olmadan da harika olabileceğinin kanıtısın! 🌈",
            "Bu yolculukta her adım, daha sağlıklı bir geleceğe açılan kapı! 🚪",
            "Geçmişte verdiğin en iyi kararlardan biri, bugün ödüllerini veriyor! 💎",
            "Zorluklarla baş etme gücün, hayal ettiğinden çok daha güçlü! 💫",
            "Şu an yaptığın fedakarlık, gelecekteki en büyük kazancın! 📈",
            "Kendine olan güvenin her geçen gün artıyor! İnanılmazsın! ⭐",
            "Sigara içmeyerek, kendini sevmenin en güzel yolunu seçtin! 💝",
            "Her yeni gün, temiz bir nefes alma özgürlüğün! 🌬️",
            "Bu süreçte öğrendiğin disiplin, hayatının her alanına yayılacak! 🎯",
            "Sigarasız bir hayat, gerçekten yaşanmış bir hayattır! 🌺",
            "İrade gösteriyorsun ve bu inanılmaz bir başarı! 🎖️",
            "Vücudun sana teşekkür ediyor, her hücren yenileniyor! 🔬",
            "Bugün kendini hiç bu kadar gurur verici hissetmemiştin! 🦸",
            "Zorluğun ötesinde büyük bir özgürlük var ve sen oradasın! 🗽",
            "Kendine olan sevgin ve saygın, sigarayı bırakmakla başladı! 👑",
            "Her geçen gün biraz daha hafifledin, biraz daha güçlendin! 🌸",
            "Sigara dumanı yerine hayallerinin peşinden koşuyorsun artık! 🌠",
            "Bu karar senin, bu başarı senin, bu gurur senin! 🏅",
            "Eski ben gitti, yeni ben daha güçlü ve sağlıklı! 🦅",
            "Her zorluğun üstesinden geldin, bundan sonraki her şey daha kolay! 🌄",
            "Sigarasız olmak bir süper güç! Ve sen bu güce sahipsin! ⚡",
            "Sağlığın için attığın her adım, sevdiklerin için de bir hediye! 🎀",
            "Artık nefes almak daha kolay, yaşamak daha güzel! 🍃",
            "Bağımlılık seni kontrol etmiyordu, sen kontrol ediyorsun! 🎮",
            "Her sabah uyanmak artık daha enerjik ve daha umut dolu! ☀️",
            "Sigarasız geçen her gün, özgüvene bir adım daha yakın! 🌟",
            "İçindeki savaşçıyı keşfettin ve kazanıyorsun! ⚔️",
            "Kendine yaptığın bu yatırım, en değerli yatırım! 💰",
            "Hayatına yeni bir sayfa açtın ve bu sayfa muhteşem! 📖",
            "Sigara yerine, kendine zaman ayırıyorsun artık! ⏰",
            "Her geçen saat, bağımlılıktan uzaklaştığın bir fırsat! 🕐",
            "Temiz akciğerlerle soluduğun her nefes bir kutlama! 🎊",
            "Artık sigara kokmuyor, özgürlük kokuyorsun! 🌹",
            "İradeni test ettin ve galip geldin! 🥇",
            "Bu yolda yalnız değilsin, kendi gücün yanında! 🤝",
            "Sağlıklı yaşam tarzın, etrafındakilere de ilham veriyor! 💡",
            "Her gün biraz daha parlak bir gelecek inşa ediyorsun! 🏗️",
            "Artık parayı daha anlamlı şeylere harcıyorsun! 💳",
            "Sigarayı bırakmak, sadece başlangıç. Sınırın yok! 🚁",
            "Kendine verdiğin söze sadık kaldın, ne kadar güçlüsün! 🤞",
            "Her gün biraz daha özgür, biraz daha mutlusun! 😊",
            "Vücudun yeniden canlanıyor, hisset bu enerjiyi! ⚡",
            "Sigarasız yaşamın tadına vardıkça, eskiye dönmek istemezsin! 🍰",
            "Bu kararı aldığın için kendini kutla! 🥳",
            "Hayatının kontrolü artık tamamen senin ellerinde! 🎛️",
            "Her yeni günde, daha güçlü bir insan olarak uyanıyorsun! 🦁",
            "Sigara bırakmanın zorluğunu yendin, artık her şey mümkün! 🌍",
            "Sağlığına yaptığın bu iyiliği hiç unutma! 🩺",
            "Temiz bir yaşam, temiz bir vicdan demek! 🕊️",
            "Her gün biraz daha dinç, biraz daha sağlıklısın! 💪",
            "Sigara içmeyen yeni sen, daha cesur ve kararlı! 🦸‍♀️",
            "Bağımlılığı yenmen, senin en büyük zaferlerinden biri! 🏆",
            "Artık koku değil, sağlık saçıyorsun! 🌼",
            "İçindeki gücü keşfettin ve bu seni durduramaz yapıyor! 🔥",
            "Her sigarasız gün, bir başarı hikayesi! 📚",
            "Kendine olan inancın, dağları bile yerinden oynatır! ⛰️",
            "Artık ciğerlerin özgürce nefes alabiliyor! 🫁",
            "Sigarayı bırakmak, hayatının en iyi kararıydı! ✅",
            "Her gün biraz daha parlıyorsun, fark ediliyor! ✨",
            "Sağlıklı olmak için attığın adımlar, paha biçilemez! 💎",
            "Artık sigara molası değil, hayat molası veriyorsun! ☕",
            "İçindeki disiplini herkese gösterdin! 📏",
            "Sigarasız yaşam, en değerli mücevherin! 💍",
            "Her sabah aynaya baktığında, daha gururlu hissediyorsun! 🪞",
            "Kendine olan saygın, sigarayı bırakmayla zirve yaptı! 🏔️",
            "Artık nefes darlığı değil, özgürlük soluyorsun! 🌊",
            "Bu yolda attığın her adım, bir kahramanlık hikayesi! 🦸‍♂️",
            "Sigarayı bırakmak, sadece bir alışkanlık değiştirmek değil, hayat değiştirmektir! 🔄",
            "Her gün biraz daha enerjik ve hayat dolusun! 🎆",
            "Artık sigara dumanı değil, başarı kokusu geliyor! 🌟",
            "Kendine yaptığın bu iyilik, asla unutulmayacak! 🎗️",
            "Sağlıklı yaşam tarzın, senin en büyük zenginliğin! 🏰",
            "Her sigarasız an, bir özgürlük anı! 🕊️",
            "İradeni gösterdin ve kazandın, işte bu kadar basit! 👍",
            "Artık sigara yerine, sevdiklerinle daha fazla vakit geçiriyorsun! 👨‍👩‍👧‍👦",
            "Her gün biraz daha sağlıklı, biraz daha mutlu! 😄",
            "Sigarayı bırakmak, kendine olan en büyük sevgi gösterisi! 💖",
            "Artık bağımlılık değil, özgürlük seni tanımlıyor! 🗝️",
            "Her nefeste hissettiğin temizlik, inanılmaz! 🧼",
            "Kendine olan güvenin, her geçen gün daha da artıyor! 📈",
            "Sigarasız olmak, senin süper gücün! 🦹",
            "Bu yolculukta her adımın bir ders, her günün bir zafer! 🎓",
            "Artık sigara içmeyen biri olarak, daha iyi bir rol modelsin! 👔",
            "Her gün biraz daha özgür hissediyorsun, değil mi? 🎈",
            "Sağlığına yaptığın bu yatırımın karşılığını her gün alıyorsun! 📊",
            "Sigarayı bırakmak, hayatının dönüm noktasıydı! 🔄",
            "Artık daha dinç, daha enerjik ve daha zinde hissediyorsun! 🏃",
            "İçindeki gücü ortaya çıkardın ve herkese gösterdin! 💪",
            "Her sigarasız gün, bir başarı madalyası! 🥇",
            "Kendine olan sevgin, sigarayı bırakmayla daha da arttı! ❤️‍🔥",
            "Artık sigara değil, hayaller peşinde koşuyorsun! 🌠",
            "Her gün biraz daha güçlü, biraz daha kararlısın! 🛡️",
            "Sigarayı bırakmak, senin en büyük başarılarından biri! 🎖️",
            "Artık temiz nefes alıyorsun ve bu paha biçilemez! 💨",
            "İçindeki savaşçı ruhu keşfettin ve kazandın! ⚔️",
            "Her yeni gün, yeni bir başlangıç ve yeni bir fırsat! 🌅",
            "Sigarasız yaşam tarzın, seni daha da çekici yapıyor! 💫",
            "Kendine olan inancın, dağları bile yerinden oynatabilir! 🏔️",
            "Artık sigara kokmuyor, hayat kokuyorsun! 🌺",
            "Her geçen gün, bağımlılıktan daha da uzaklaşıyorsun! 🚶",
            "Sağlıklı olmak için verdiğin mücadele, takdire şayan! 👏",
            "Artık sigara molası değil, kendine zaman ayırıyorsun! 🧘",
            "İçindeki gücü herkese gösterdin, ne kadar harikasın! 🌟",
            "Her sigarasız an, özgürlüğe bir adım daha yakın! 🚪",
            "Sigarayı bırakmak, hayatının en iyi kararlarından biriydi! ✅",
            "Artık daha dinç, daha enerjik ve daha mutlusun! 😊",
            "Kendine yaptığın bu iyiliği asla unutma! 🎁",
            "Her gün biraz daha sağlıklı, biraz daha özgürsün! 🕊️",
            "Sigarasız olmak, senin en büyük gücün! ⚡",
            "İçindeki disiplini gösterdin ve kazandın! 🏅",
            "Artık sigara değil, sağlık ve mutluluk önceliğin! 💚",
            "Her yeni günde, daha güçlü bir insan olarak uyanıyorsun! 🌄"
        ];
